ARG AIRFLOW_IMAGE_NAME=apache/airflow:2.7.2
FROM ${AIRFLOW_IMAGE_NAME}

USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends unzip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir --user -r /tmp/requirements.txt
