# -*- coding: utf-8 -*-
"""capstone

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CZXppxPBVd5lXkLf-ubgvfgIsSs88rC8
"""

print('Full Name: Sudheer Karanam')
print('Uplevel Email Address: sudkar.msc@gmail.com')
print('Name of the Problem Statement of Submission: MediWatch: likelihood of patient readmission')

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

def preprocess_data():
  dfRaw=pd.read_csv(os.getenv('RAW_INPUT_FILE_PATH'))
  dfRaw.info()

  """Observation:
  1. The dataset contains columns with numeric and object datatypes, except for max_glu_serum and A1Cresult all other columns have full non-null values.
  """

  #Check for first few rows : any findings ?
  dfRaw.head()

  """Observation:
  1. Patient_nbr and encounter_id may be unique throughout and can be dropped.
  2. Data is probable mix of numeric, boolean and object types
  3. Weight data is not present (to be dropped)
  4. Age columns needs encoding
  """

  #Check for structure - datatypes and number of not nulls
  dfRaw.notnull().sum()

  #Check for any duplicates
  dfRaw.duplicated().sum()

  """Observation:
  1. No duplicates found
  """

  dfRaw.shape

  #Check the missing values across columns
  dfRaw.isna().sum()

  """Observation:
  1. max_glu_serum and A1Cresult has approx 90% data missing, lets get rid of them
  """

  dfRaw['gender'].value_counts() #

  """Observation:
  1. gender has missing values for 3 rows, remove those records
  """



  #Check for target variable's balance
  ycounts=dfRaw['readmitted'].value_counts()
  fig, axes = plt.subplots(nrows=1, ncols=2, figsize=(15,5))
  sns.barplot(x=dfRaw['readmitted'].value_counts().index, y=dfRaw['readmitted'].value_counts().values, ax=axes[0])
  axes[0].set_title('Distribution of value counts for target vairable readmitted')
  axes[0].set_xlabel('Readmitted')
  axes[0].set_ylabel('Count')

  plt.pie(ycounts, labels=ycounts.index, autopct='%1.1f%%')
  axes[1].set_title('Distribution of value counts for target variable reAdmission Status')

  plt.tight_layout()
  #plt.show()

  """Observation:
  1. Target is slightly tilted towards 'NO', else looks like an even distribution.
  2. Predicting a readmission eligible person as NO (false negative) can have severe consequences.
  3. Hence recall and f1_score will be important metrics.

  **Data Pre-Processing**
  """

  #print(dfRaw['race'].value_counts()) # has few missing values, replace missing with majority value: Caucasian
  #print(dfRaw['age'].value_counts())
  #print(dfRaw['max_glu_serum'].value_counts()) #>90% of missing values, remove the column
  #print(dfRaw['A1Cresult'].value_counts())  #>90% of missing values, remove the column
  #print(dfRaw['weight'].value_counts())  #>90% of missing values, remove the column
  #print(dfRaw['admission_type_id'].value_counts())
  #print(dfRaw['discharge_disposition_id'].value_counts())
  #print(dfRaw['admission_source_id'].value_counts())
  #print(dfRaw['time_in_hospital'].value_counts())
  #print(dfRaw['payer_code'].value_counts()) # has 50% missing data, lets remove it is more of admin info
  #print(dfRaw['medical_specialty'].value_counts() # has 50% missing data, lets remove it is more of admin info
  #print(dfRaw['examide'].value_counts()) # has only one value, not relevant, so remove the column
  #print(dfRaw['citoglipton'].value_counts()) # has only one value, not relevant, so remove the column
  #print( (dfRaw['diag_3']=='V57').sum()) # has an alpha numeric values v57, encode them
  #print( len(dfRaw))

  #Data cleaning:
  dfDataClean=dfRaw.copy()
  dfDataClean.drop(['max_glu_serum', 'A1Cresult', 'weight','encounter_id','patient_nbr','payer_code','medical_specialty','examide','citoglipton'], axis=1, inplace=True)
  dfDataClean=dfDataClean[dfDataClean['gender']!='Unknown/Invalid']
  dfDataClean.loc[dfDataClean['race'] == "?", 'race'] = str('Caucasian')
  #dfDataClean = dfDataClean[dfDataClean['diag_3'] != 'V57']
  #dfDataClean = dfDataClean[dfDataClean['diag_3'] != 'V27']

  #print(dfDataClean['race'].value_counts())
  #print(len(dfDataClean))

  import math
  #EDA
  cols_for_eda = [col for col in dfDataClean.columns if col != 'readmitted']
  #cols=['race','gender','age','admission_type_id','discharge_disposition_id','time_in_hospital','payer_code']

  ncols = 3
  nrows = math.ceil(len(cols_for_eda) / ncols)

  fig,axes=plt.subplots(nrows=nrows, ncols=ncols, figsize=(15,nrows*3)) # Adjust figsize dynamically
  axes=axes.flatten()

  for i, col in enumerate(cols_for_eda): # Iterate over the filtered columns
    #print(col)
    normalizedCounts=dfDataClean.groupby(col)['readmitted'].value_counts(normalize=True).unstack()
    normalizedCounts.plot(kind='bar', stacked=True,ax=axes[i])
    axes[i].set_title(f"Default rate Readmitted by {col}")
    axes[i].set_ylabel("Proportion")
    axes[i].set_xlabel(col)
    axes[i].tick_params(axis='x',rotation=45)

  # Hide any unused subplots
  for j in range(len(cols_for_eda), len(axes)):
      fig.delaxes(axes[j])

  plt.tight_layout()
  #plt.show()
  
  objectCols = ['race', 'gender', 'age','diag_1','diag_2','diag_3','metformin', 'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide', 'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone', 'tolazamide', 'insulin', 'glyburide-metformin', 'glipizide-metformin', 'glimepiride-pioglitazone', 'metformin-rosiglitazone', 'metformin-pioglitazone', 'change', 'diabetesMed']
  print(objectCols)
  #Perform ohe for all category columns
  map={}
  for col in objectCols:
    dfDataClean[col]=dfDataClean[col].astype('category')
    code_to_label = dict(enumerate(dfDataClean[col].cat.categories))
    dfDataClean[col+'_encoded']=dfDataClean[col].cat.codes
    print(f"{col} --- {code_to_label}")
    map[col]=code_to_label
  print(map)

  #Perform label encoding for target column
  #from sklearn.preprocessing import LabelEncoder
  #le = LabelEncoder()
  dfDataClean['readmitted']=dfDataClean['readmitted'].astype('category')
  code_to_label2 = dict(enumerate(dfDataClean['readmitted'].cat.categories))
  #print(code_to_label2)
  dfDataClean['readmitted']=dfDataClean['readmitted'].cat.codes

  dfDataCleanCorr=dfDataClean.copy()
  dfDataCleanCorr.drop(objectCols, axis=1, inplace=True)
  dfDataCleanCorr=dfDataCleanCorr.sort_index(axis=1)
  plt.figure(figsize=(50,25))
  sns.heatmap(dfDataCleanCorr.corr(), annot=True, cmap='coolwarm')
  #plt.show()

  """Observation:
  1. Heatmap does not show any strong co-relation between columns

  """
  dfDataCleanCorr.to_csv(os.getenv('PREPROCESSED_FILE_PATH'), index=False)

if __name__ == "__main__":
  preprocess_data()