FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y build-essential curl 
RUN rm -rf /var/lib/apt/lists/*

#Install python dependenices
ENV PIP_REQUIRE_HASHES=false
COPY ./requirements.txt .
RUN pip install -r requirements.txt

#COPY application code
COPY . .

#Create necessary dir
RUN mkdir -p /app/data /app/models /app/logs

#Default command
CMD ["python", "train.py"]

