FROM python:3.12-slim

RUN apt-get update && apt-get install -y build-essential curl 
RUN rm -rf /var/lib/apt/lists/*

#Install python dependenices
RUN mkdir -p /app/mediwatch
WORKDIR /app/mediwatch

COPY ./requirements.txt .
RUN pip install -r requirements.txt

#COPY application code
COPY . /app/mediwatch/

ENV PIP_REQUIRE_HASHES=false
ENV PYTHONPATH=".:/app/mediwatch/data_preprocessing_scripts:/app/mediwatch/models/scripts"
ENV PREPROCESSING_TRAINING_MODEL_PORT=8811
ENV HOME_PATH="/app/mediwatch"
ENV RAW_INPUT_FILE_PATH=$HOME_PATH"/data/diabetic_data_raw.csv"
ENV PREPROCESSED_FILE_PATH=$HOME_PATH"/data/diabetic_data_processed.csv"
ENV GIT_PYTHON_REFRESH="quiet"
ENV MODEL_FILE="./models/modelStore/mediwatch.joblib"

EXPOSE $PREPROCESSING_TRAINING_PORT
EXPOSE 5050

#Default command
#CMD ["python", "webapp/webAppForPreprocessing.py"]
#CMD ["sh", "-c", "mlflow ui --port 5050 &", "&&", "exec python webapp/webAppForPreprocessing.py"]
CMD mlflow ui --port 5050 & python webapp/webAppForPreprocessing.py

