# Faster MLflow build with binary wheels
FROM python:3.12

WORKDIR /app

# Install system dependencies for numpy/scipy/sqlalchemy
RUN apt-get update && apt-get install -y \
    build-essential gfortran \
    liblapack-dev libblas-dev \
    && rm -rf /var/lib/apt/lists/*

ENV PIP_REQUIRE_HASHES=false    
# Upgrade pip tooling
RUN pip install --upgrade pip setuptools wheel

# Install MLflow and boto3 with prebuilt binaries
RUN pip install --no-cache-dir --prefer-binary mlflow

# Set environment variables for MLflow
ENV MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow/mlflow.db 

RUN mkdir -p /app/mlflow
RUN chmod -R 755 /app

EXPOSE 5050

CMD ["mlflow", "server", \
     "--backend-store-uri", "sqlite:///mlflow/mlflow.db", \
     "--host", "0.0.0.0", "--port", "5050", \
     "--allowed-hosts", "*"]
